---

platform: linux

image_resource:
  type: docker-image
  source: {repository: nsxedgegen/nsx-edge-gen-worker}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OM_VM_NAME:
  GOVC_INSECURE:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_DATACENTER:
  GOVC_NETWORK:
  GOVC_RESOURCE_POOL:
  OM_VM_NAME:
  GOVC_NETWORK:
  GOVC_RESOURCE_POOL:
  GOVC_HOST:

inputs:
  - name: nsx-ci-pipeline
  - name: govc

run:
  path: nsx-ci-pipeline/tasks/delete-opsman/task.sh
