---

platform: linux

image_resource:
  type: docker-image
  source: {repository: nsxedgegen/nsx-edge-gen-worker}

params:
  GOVC_INSECURE:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_DATACENTER:
  OM_VM_NAME:

inputs:
  - name: concourse-vsphere
  - name: govc

run:
  path: concourse-vsphere/tasks/delete-opsman/task.sh
