---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_IP:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:

inputs:
  - name: concourse-vsphere
  - name: govc

run:
  path: concourse-vsphere/tasks/delete-opsman/task.sh
