---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: nsxedgegen/nsx-edge-gen-worker

params:  
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  AZ_ERT_SINGLETON:
  AZS_ERT:
  NETWORK_NAME:
  ENABLE_SECURITY_EVENT_LOGGING:
  SYSLOG_HOST:
  SYSLOG_PORT:
  SYSLOG_PROTOCOL:
  SYSLOG_DRAIN_BUFFER_SIZE:
  LOGGREGATOR_ENDPOINT_PORT:    
  SSL_TERMINATION:
  OPS_MGR_GENERATE_SSL_ENDPOINT:
  DISABLE_HTTP_PROXY:
  TCP_ROUTING:
  TCP_ROUTING_PORTS:
  ROUTE_SERVICES:
  IGNORE_SSL_CERT:
  COMPANY_NAME:
  AUTHENTICATION_MODE:
  SMTP_FROM:
  SMTP_ADDRESS:
  SMTP_PORT:
  SMTP_USER:
  SMTP_PWD:
  SMTP_AUTH_MECHANISM:
  LDAP_URL:
  LDAP_USER:
  LDAP_PWD:
  SEARCH_BASE:
  SEARCH_FILTER:
  GROUP_SEARCH_BASE:
  GROUP_SEARCH_FILTER:
  MAIL_ATTR_NAME:
  FIRST_NAME_ATTR:
  LAST_NAME_ATTR:
  SYSTEM_DOMAIN:
  APPS_DOMAIN:
  DEFAULT_QUOTA_MEMORY_LIMIT_IN_MB:
  DEFAULT_QUOTA_MAX_SERVICES_COUNT:
  SSL_CERT:
  SSL_PRIVATE_KEY:
  SAML_SSL_CERT:
  SAML_SSL_PRIVATE_KEY:
  HAPROXY_FORWARD_TLS:
  HAPROXY_BACKEND_CA:
  ROUTER_TLS_CIPHERS:
  HAPROXY_TLS_CIPHERS:
  DISABLE_HTTP_PROXY:
  TCP_ROUTING:
  TCP_ROUTING_PORTS:
  ROUTE_SERVICES:
  IGNORE_SSL_CERT:
  SECURITY_ACKNOWLEDGEMENT:
  ENABLE_SECURITY_EVENT_LOGGING:
  HA_PROXY_IPS:
  SKIP_CERT_VERIFY:
  DISABLE_INSECURE_COOKIES:
  ROUTER_STATIC_IPS:
  ROUTER_REQUEST_TIMEOUT_IN_SEC:
  GARDEN_NETWORK_POOL_CIDR:
  MYSQL_MONITOR_EMAIL:
  MYSQL_BACKUPS:
  MYSQL_BACKUPS_SCP_SERVER:
  MYSQL_BACKUPS_SCP_PORT:
  MYSQL_BACKUPS_SCP_USER:
  MYSQL_BACKUPS_SCP_KEY:
  MYSQL_BACKUPS_SCP_DESTINATION:
  MYSQL_BACKUPS_SCP_CRON_SCHEDULE:
  MYSQL_BACKUPS_S3_ENDPOINT_URL:
  MYSQL_BACKUPS_S3_BUCKET_NAME:
  MYSQL_BACKUPS_S3_BUCKET_PATH:
  MYSQL_BACKUPS_S3_ACCESS_KEY_ID:
  MYSQL_BACKUPS_S3_SECRET_ACCESS_KEY:
  MYSQL_BACKUPS_S3_CRON_SCHEDULE:
  ALLOW_APP_SSH_ACCESS:
  TCP_ROUTER_STATIC_IPS:
  SSH_STATIC_IPS:
  CONSUL_SERVER_INSTANCES:
  NATS_INSTANCES:
  NFS_SERVER_INSTANCES:
  MYSQL_PROXY_INSTANCES:
  MYSQL_INSTANCES:
  BACKUP_PREPARE_INSTANCES:
  UAA_INSTANCES:
  CLOUD_CONTROLLER_INSTANCES:
  HA_PROXY_INSTANCES:
  HA_PROXY_LB_NAME:
  HAPROXY_FLOATING_IPS:
  ROUTER_INSTANCES:
  MYSQL_MONITOR_INSTANCES:
  CLOCK_GLOBAL_INSTANCES:
  CLOUD_CONTROLLER_WORKER_INSTANCES:
  DIEGO_DATABASE_INSTANCES:
  DIEGO_BRAIN_INSTANCES:
  DIEGO_CELL_INSTANCES:
  DOPPLER_INSTANCES:
  LOGGREGATOR_TC_INSTANCES:
  TCP_ROUTER_INSTANCES:
  SYSLOG_ADAPTER_INSTANCES:
  INTERNET_CONNECTED:
  CONTAINER_NETWORKING_NW_CIDR:
  CONTAINER_NETWORKING_INTERFACE_PLUGIN:
  CREDHUB_PASSWORD:
  DEPLOYMENT_NW_CIDR:
  NSX_APPS_MGR_NAME:
  TILE_ERT_ROUTER_SECURITY_GROUP:              
  TILE_ERT_TCP_ROUTER_SECURITY_GROUP:
  TILE_ERT_DIEGO_BRAIN_SECURITY_GROUP:
  TILE_ERT_MYSQL_PROXY_SECURITY_GROUP:
  TILE_ERT_DIEGO_CELL_SECURITY_GROUP:

inputs:
  - name: nsx-ci-pipeline
  - name: om-cli
  - name: nsx-gen-output
run:
  path: nsx-ci-pipeline/tasks/config-ert-2.0/task.sh
