---

platform: linux

image_resource:
  type: docker-image
  source: {repository: nsxedgegen/nsx-edge-gen-worker}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  TILE_AZ_SCS_SINGLETON:
  TILE_AZS_SCS:

inputs:
  - name: nsx-ci-pipeline
  - name: om-cli

run:
  path: nsx-ci-pipeline/tasks/config-scs/task.sh
