---

platform: linux

image_resource:
  type: docker-image
  source: {repository: virtmerlin/nsx-edge-gen-worker}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PIVNET_API_TOKEN:

inputs:
  - name: pivnet-er-product
  - name: concourse-vsphere
  - name: om-cli
  - name: pivnet-cli

run:
  path: concourse-vsphere/tasks/upload-er-tile/task.sh
