---

platform: linux

image_resource:
  type: docker-image
  source: {repository: virtmerlin/nsx-edge-gen-worker}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:

inputs:
  - name: concourse-vsphere
  - name: om-cli

run:
  path: concourse-vsphere/tasks/apply-changes/task.sh
