---

platform: linux

image_resource:
  type: docker-image
  source: {repository: virtmerlin/nsx-edge-gen-worker}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  TILE_AZ_MYSQL_SINGLETON:
  TILE_AZS_MYSQL:
  TILE_MYSQL_PROXY_IPS:
  TILE_MYSQL_PROXY_VIP:
  TILE_MYSQL_MONITOR_EMAIL:

inputs:
  - name: concourse-vsphere
  - name: om-cli

run:
  path: concourse-vsphere/tasks/config-mysql/task.sh
