---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  PIVNET_API_TOKEN:

inputs:
  - name: pivnet-opsman-product
  - name: pivnet-er-product
  - name: pivnet-metrics-product
  - name: concourse-vsphere
  - name: om-cli
  - name: pivnet-cli
  - name: govc

run:
  path: concourse-vsphere/tasks/download-products/task.sh
