---

platform: linux

image_resource:
  type: docker-image
  source: {repository: nsxedgegen/nsx-edge-gen-worker}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  AZ_1:
  NETWORK_NAME:
  JMX_ADMIN_USR:
  JMX_ADMIN_PWD:
  JMX_SECURITY_LOGGING:
  JMX_USE_SSL:

inputs:
  - name: nsx-ci-pipeline
  - name: om-cli
  - name: nsx-gen-output
  
run:
  path: nsx-ci-pipeline/tasks/config-ops-metrics/task.sh
