---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  AZ_1:
  NETWORK_NAME:
  JMX_ADMIN_USR:
  JMX_ADMIN_PWD:
  JMX_SECURITY_LOGGING:
  JMX_USE_SSL:

inputs:
  - name: concourse-vsphere
  - name: om-cli

run:
  path: concourse-vsphere/tasks/config-ops-metrics/task.sh
