---

platform: linux

image_resource:
  type: docker-image
  source: {repository: nsxedgegen/nsx-edge-gen-worker}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  TILE_AZ_MYSQL_SINGLETON:
  TILE_AZS_MYSQL:
  TILE_MYSQL_PROXY_IPS:
  TILE_MYSQL_PROXY_VIP:
  TILE_MYSQL_MONITOR_EMAIL:
  TILE_MYSQL_PROXY_INSTANCES:
  TILE_MYSQL_BACKUP_PREPARE_INSTANCES:
  TILE_MYSQL_MONITORING_INSTANCES:
  TILE_MYSQL_BROKER_INSTANCES:
  TILE_MYSQL_PROXY_SECURITY_GROUP:
  TILE_MYSQLV2_PLAN1_NAME:
  TILE_MYSQLV2_PLAN1_DESCRIPTION:
  TILE_MYSQLV2_PLAN1_INSTANCE_LIMIT:
  TILE_MYSQLV2_PLAN1_ACCESS:
  TILE_MYSQLV2_PLAN1_MULTI_NODE_DEPLOYMENT:
  TILE_MYSQLV2_PLAN1_VM_TYPE:
  TILE_MYSQLV2_PLAN1_PERSISTENT_DISK_SIZE:
  TILE_MYSQLV2_PLAN2_ENABLED:
  TILE_MYSQLV2_PLAN2_NAME:
  TILE_MYSQLV2_PLAN2_DESCRIPTION:
  TILE_MYSQLV2_PLAN2_INSTANCE_LIMIT:
  TILE_MYSQLV2_PLAN2_ACCESS:
  TILE_MYSQLV2_PLAN2_MULTI_NODE_DEPLOYMENT:
  TILE_MYSQLV2_PLAN2_VM_TYPE:
  TILE_MYSQLV2_PLAN2_PERSISTENT_DISK_SIZE:
  TILE_MYSQLV2_PLAN3_ENABLED:
  TILE_MYSQLV2_PLAN3_NAME:
  TILE_MYSQLV2_PLAN3_DESCRIPTION:
  TILE_MYSQLV2_PLAN3_INSTANCE_LIMIT:
  TILE_MYSQLV2_PLAN3_ACCESS:
  TILE_MYSQLV2_PLAN3_MULTI_NODE_DEPLOYMENT:
  TILE_MYSQLV2_PLAN3_VM_TYPE:
  TILE_MYSQLV2_PLAN3_PERSISTENT_DISK_SIZE:
  TILE_MYSQLV2_PLAN4_ENABLED:
  TILE_MYSQLV2_PLAN4_NAME:
  TILE_MYSQLV2_PLAN4_DESCRIPTION:
  TILE_MYSQLV2_PLAN4_INSTANCE_LIMIT:
  TILE_MYSQLV2_PLAN4_ACCESS:
  TILE_MYSQLV2_PLAN4_MULTI_NODE_DEPLOYMENT:
  TILE_MYSQLV2_PLAN4_VM_TYPE:
  TILE_MYSQLV2_PLAN4_PERSISTENT_DISK_SIZE:
  TILE_MYSQLV2_PLAN5_ENABLED:
  TILE_MYSQLV2_PLAN5_NAME:
  TILE_MYSQLV2_PLAN5_DESCRIPTION:
  TILE_MYSQLV2_PLAN5_INSTANCE_LIMIT:
  TILE_MYSQLV2_PLAN5_ACCESS:
  TILE_MYSQLV2_PLAN5_MULTI_NODE_DEPLOYMENT:
  TILE_MYSQLV2_PLAN5_VM_TYPE:
  TILE_MYSQLV2_PLAN5_PERSISTENT_DISK_SIZE:
  TILE_MYSQLV2_BACKUP_OPTION:
  TILE_MYSQLV2_BACKUP_CRON_SCHEDULE:
  TILE_MYSQLV2_BACKUP_EMAIL_ALERTS:
  TILE_MYSQLV2_BACKUP_S3_ACCESS_ID:
  TILE_MYSQLV2_BACKUP_S3_ACCESS_KEY:
  TILE_MYSQLV2_BACKUP_S3_ENDPOINT:
  TILE_MYSQLV2_BACKUP_S3_BUCKET:
  TILE_MYSQLV2_BACKUP_S3_PATH:
  TILE_MYSQLV2_BACKUP_S3_REGION:
  TILE_MYSQLV2_BACKUP_AZURE_ACCOUNT:
  TILE_MYSQLV2_BACKUP_AZURE_KEY:
  TILE_MYSQLV2_BACKUP_AZURE_PATH:
  TILE_MYSQLV2_BACKUP_AZURE_BLOBSTORE:
  TILE_MYSQLV2_BACKUP_SCP_USER:
  TILE_MYSQLV2_BACKUP_SCP_SERVER:
  TILE_MYSQLV2_BACKUP_SCP_DESTINATION:
  TILE_MYSQLV2_BACKUP_SCP_FINGERPRINT:
  TILE_MYSQLV2_BACKUP_SCP_KEY:
  TILE_MYSQLV2_BACKUP_SCP_PORT:
  TILE_MYSQLV2_BACKUP_GCS_PROJECT:
  TILE_MYSQLV2_BACKUP_GCS_BUCKET:
  TILE_MYSQLV2_BACKUP_GCS_SERVICE_ACCOUNT:


inputs:
  - name: nsx-ci-pipeline
  - name: om-cli
  - name: nsx-gen-output

run:
  path: nsx-ci-pipeline/tasks/config-mysqlv2/task.sh
