---

platform: linux

image_resource:
  type: docker-image
  source: {repository: nsxedgegen/nsx-edge-gen-worker}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PIVNET_API_TOKEN:
  OM_IP:
  NO_PROXY:    
  IAAS:

inputs:
  - name: pivnet-product
  - name: nsx-ci-pipeline
  - name: om-cli
  - name: pivnet-cli



run:
  path: nsx-ci-pipeline/tasks/upload-product-and-stemcell/task.sh
