---

platform: linux

image_resource:
  type: docker-image
  source: {repository: virtmerlin/nsx-edge-gen-worker}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  AZ_ERT_SINGLETON:
  AZS_ERT:
  NETWORK_NAME:
  SYSLOG_HOST:
  SYSLOG_PORT:
  SYSLOG_PROTOCOL:
  LOGGREGATOR_ENDPOINT_PORT:
  NETWORK_POINT_OF_ENTRY:
  SSL_CERT:
  SSL_PRIVATE_KEY:
  DISABLE_HTTP_PROXY:
  TCP_ROUTING:
  TCP_ROUTING_PORTS:
  ROUTE_SERVICES:
  IGNORE_SSL_CERT:
  SMTP_FROM:
  SMTP_ADDRESS:
  SMTP_PORT:
  SMTP_USER:
  SMTP_PWD:
  SMTP_AUTH_MECHANISM:
  UAA_METHOD:
  LDAP_URL:
  LDAP_USER:
  LDAP_PWD:
  SEARCH_BASE:
  SEARCH_FILTER:
  GROUP_SEARCH_BASE:
  GROUP_SEARCH_FILTER:
  MAIL_ATTR_NAME:
  FIRST_NAME_ATTR:
  LAST_NAME_ATTR:
  SYSTEM_DOMAIN:
  APPS_DOMAIN:
  HA_PROXY_IPS:
  SKIP_CERT_VERIFY:
  ROUTER_STATIC_IPS:
  MYSQL_MONITOR_EMAIL:
  TCP_ROUTER_STATIC_IPS:
  SSH_STATIC_IPS:
  ERT_MYSQL_STATIC_IPS:
  CONSUL_SERVER_INSTANCES:
  NATS_INSTANCES:
  ETCD_TLS_SERVER_INSTANCES:
  NFS_SERVER_INSTANCES:
  MYSQL_PROXY_INSTANCES:
  MYSQL_INSTANCES:
  BACKUP_PREPARE_INSTANCES:
  CCDB_INSTANCES:
  UAADB_INSTANCES:
  UAA_INSTANCES:
  CLOUD_CONTROLLER_INSTANCES:
  HA_PROXY_INSTANCES:
  ROUTER_INSTANCES:
  MYSQL_MONITOR_INSTANCES:
  CLOCK_GLOBAL_INSTANCES:
  CLOUD_CONTROLLER_WORKER_INSTANCES:
  DIEGO_DATABASE_INSTANCES:
  DIEGO_BRAIN_INSTANCES:
  DIEGO_CELL_INSTANCES:
  DOPPLER_INSTANCES:
  LOGGREGATOR_TC_INSTANCES:
  TCP_ROUTER_INSTANCES:

inputs:
  - name: concourse-vsphere
  - name: om-cli

run:
  path: concourse-vsphere/tasks/config-ert/task.sh
