---

platform: linux

image_resource:
  type: docker-image
  source: {repository: nsxedgegen/nsx-edge-gen-worker}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  AZ_ERT_SINGLETON:
  AZS_ERT:
  NETWORK_NAME:
  SYSLOG_HOST:
  SYSLOG_PORT:
  SYSLOG_PROTOCOL:
  SYSLOG_DRAIN_BUFFER_SIZE:
  ENABLE_SECURITY_EVENT_LOGGING:
  LOGGREGATOR_ENDPOINT_PORT:
  SSL_TERMINATION:
  SSL_CERT:
  SSL_PRIVATE_KEY:
  OPS_MGR_GENERATE_SSL_ENDPOINT:
  DISABLE_HTTP_PROXY:
  TCP_ROUTING:
  TCP_ROUTING_PORTS:
  ROUTE_SERVICES:
  IGNORE_SSL_CERT:
  SMTP_FROM:
  SMTP_ADDRESS:
  SMTP_PORT:
  SMTP_USER:
  SMTP_PWD:
  SMTP_AUTH_MECHANISM:
  AUTHENTICATION_MODE:
  LDAP_URL:
  LDAP_USER:
  LDAP_PWD:
  SEARCH_BASE:
  SEARCH_FILTER:
  GROUP_SEARCH_BASE:
  GROUP_SEARCH_FILTER:
  MAIL_ATTR_NAME:
  FIRST_NAME_ATTR:
  LAST_NAME_ATTR:
  SYSTEM_DOMAIN:
  APPS_DOMAIN:
  HA_PROXY_IPS:
  SKIP_CERT_VERIFY:
  ROUTER_STATIC_IPS:
  MYSQL_MONITOR_EMAIL:
  TCP_ROUTER_STATIC_IPS:
  SSH_STATIC_IPS:
  ERT_MYSQL_STATIC_IPS:
  CONSUL_SERVER_INSTANCES:
  NATS_INSTANCES:
  ETCD_TLS_SERVER_INSTANCES:
  NFS_SERVER_INSTANCES:
  MYSQL_PROXY_INSTANCES:
  MYSQL_INSTANCES:
  BACKUP_PREPARE_INSTANCES:
  CCDB_INSTANCES:
  UAADB_INSTANCES:
  UAA_INSTANCES:
  CLOUD_CONTROLLER_INSTANCES:
  HA_PROXY_INSTANCES:
  ROUTER_INSTANCES:
  MYSQL_MONITOR_INSTANCES:
  CLOCK_GLOBAL_INSTANCES:
  CLOUD_CONTROLLER_WORKER_INSTANCES:
  DIEGO_DATABASE_INSTANCES:
  DIEGO_BRAIN_INSTANCES:
  DIEGO_CELL_INSTANCES:
  DOPPLER_INSTANCES:
  LOGGREGATOR_TC_INSTANCES:
  TCP_ROUTER_INSTANCES:
  DEPLOYMENT_NW_CIDR:
  NSX_APPS_MGR_NAME:
  COMPANY_NAME:  
  TILE_ERT_ENABLE_C2C:
  TILE_ERT_C2C_NETWORK_CIDR:
  TILE_ERT_C2C_VTEP_PORT:
  TILE_ERT_ROUTER_SECURITY_GROUP:              
  TILE_ERT_TCP_ROUTER_SECURITY_GROUP:
  TILE_ERT_DIEGO_BRAIN_SECURITY_GROUP:
  TILE_ERT_MYSQL_PROXY_SECURITY_GROUP:
  TILE_ERT_DIEGO_CELL_SECURITY_GROUP:
  COMPANY_NAME:
  GARDEN_NETWORK_MTU:
  GARDEN_NETWORK_POOL_CIDR:
  ALLOW_APP_SSH_ACCESS:
  INTERNET_CONNECTED:
  SECURITY_ACKNOWLEDGEMENT:
  DISABLE_INSECURE_COOKIES:
  CONTAINER_NETWORKING_NW_CIDR:
  CONTAINER_NETWORKING_INTERFACE_PLUGIN:
    
inputs:
  - name: nsx-ci-pipeline
  - name: om-cli
  - name: nsx-gen-output
  
run:
  path: nsx-ci-pipeline/tasks/config-ert/task.sh
