---

platform: linux

image_resource:
  type: docker-image
  source: {repository: virtmerlin/nsx-edge-gen-worker}

params:
  GOVC_INSECURE:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_DATACENTER:
  GOVC_DATASTORE:
  GOVC_NETWORK:
  GOVC_RESOURCE_POOL:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OPS_MGR_SSH_PWD:
  OM_DECRYPTION_PWD:
  OM_NTP_SERVERS:
  OM_DNS_SERVERS:
  OM_GATEWAY:
  OM_NETMASK:
  OM_IP:
  OM_VM_NETWORK:
  OM_VM_NAME:
  OM_RESOURCE_POOL:
  OM_DISK_TYPE:
  OM_VM_POWER_STATE:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATA_CENTER:
  NSX_EDGE_GEN_NSX_MANAGER_ADDRESS:
  NSX_EDGE_GEN_NSX_MANAGER_ADMIN_USER:
  NSX_EDGE_GEN_NSX_MANAGER_ADMIN_PASSWD:
  NSX_EDGE_GEN_NSX_MANAGER_TRANSPORT_ZONE:
  NSX_EDGE_GEN_EDGE_DATASTORE:
  NSX_EDGE_GEN_EDGE_CLUSTER:
  NSX_EDGE_GEN_NAME:


inputs:
  - name: pivnet-opsman-product
  - name: concourse-vsphere
  - name: govc
  - name: nsx-edge-gen

run:
  path: concourse-vsphere/tasks/import-opsman/task.sh
